### ISSUE TITLE
Make the embedded links look better for each link

### ISSUE THREAD

**Issue by nicknamenamenick** [ublue-os/docs.bazzite.gg#40]
Images and descriptions would be nice for _most_ of the documentation.  The homepage for https://docs.bazzite.gg should not be changed for the embed in my opinion.

Example of embed link CSS:
```
---
authors:
  - "@nicknamenamenick"
# preview: "../img/distrobox.png"
preview:
  alpha: 150
  image: "../img/distrobox.png"
description: ""
---
```
